app:
  #image: jmaya/mediahub_app
  build: .
  command: bundle exec foreman run web
  # volumes:
  #   # - /mnt/MediaHub:/myapp/public/uploads
  #    - ./public/uploads:/myapp/public/uploads
  #    - ./tmp:/myapp/tmp
  #    - ./log:/myapp/log
  environment:
    - PORT=3000
    - VIRTUAL_HOST=mediahub.lasamaria.com
  links:
    - db
    - redis

sidekiq:
  build: .
  # image: jmaya/mediahub_app
  command: bundle exec sidekiq
  environment:
    - REDIS_URL=redis://redis:6379
  volumes_from:
    - app
  links:
    - db
    - redis

web:
  image: jwilder/nginx-proxy
  ports:
    - "8080:80"
  # volumes:
  #   - ./config/container/myapp.conf:/etc/nginx/conf.d/myapp.conf
  volumes_from:
    - app
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  links:
    - app

db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin
  # volumes:
  #   - ./data:/var/lib/postgresql/data

redis:
  image: redis
  ports:
    - "6379:6379"
